name: haicor-experiment
channels:
  - defaults
  - vnmabus
dependencies:
  - ipython
  - pylint
  - autopep8
  - matplotlib
  - jupyter
  - numpy
  - nose
  - pandas
  - scipy
  - sympy
  - python
  - dcor
